### ISSUE TITLE
self.request() sometimes returns results when service type and method don't match.

### ISSUE THREAD

**Issue by fenfir** [deliveryhero/lymph#263]
If I call self.request with a service type that doesn't match the method name, Some of the time it generates  warning like: '2015-10-16 11:40:51,205 [WARNING] lymph.core.container: unsupported service type: echo - trace_id="7c4a6eed669b44e0b0decc1189c9a02c"' and throws a lymph.RpcError, but others it returns a value.

result = self.request('lymph', 'echo.upper', { 'text' : 'delay_%f' % self.delay } )

I am not sure which is the incorrect behavior. I may not be understanding the encapsulation, but the demos made it seem as if the service type was the parent of the method name, in which case I would expect the above to fail. 

Here is some code to reproduce the problem, it uses the same config as demo
```python
from __future__ import print_function, unicode_literals

import time
import random
import gevent
import lymph
from lymph.core import trace

class Client(lymph.Interface):
    delay = 2.0

    def on_start(self):
        super(Client, self).on_start()
        gevent.spawn(self.loop)

    def apply_config(self, config):
        super(Client, self).apply_config(config);
        self.delay = config.get('delay', 2.0)

    def loop(self):
        while self.delay > .05:
            time.sleep(self.delay)
            trace.set_id()
            try:
                result = self.request('lymph', 'echo.upper', { 'text' : 'delay_%f' % self.delay } )
            except lymph.RpcError:
                print("RpcError (retry)")
                continue

            print("result = %s" % result._body)
            self.delay = self.delay / 2
```

**Comment by emulbreh** [comment]
Service instances can expose more than one interface, and all instances provide the lymph interface. This is why you see instances more than once with ``lymph discover --instances``.
In your example you'll sometimes send ``echo.upper`` requests to instances that don't implement ``echo``, thus the warning. 

The name that's used to lookup instances doesn't always have to be equal to the name of the interface the called method belongs to, e.g. ``lymph request --address echo lymph.inspect '{}'`` works because all instances of ``echo`` also expose ``lymph``.
